vscode:
  extensions:
    - vscjava.vscode-java-pack
    - eamodio.gitlens
    - esbenp.prettier-vscode

tasks:
  - before: sh ./scripts/download-jars.sh
    init: sh ./scripts/compile.sh
    command: sh ./scripts/run-tests.sh